# docker-compose up
# docker stack deploy --compose-file=docker-stack.yml voting_stack
version: "3"
services:
  coreapi:
    # image: cloudworkloadcoreapi
    build: ./
    # networks:
    #   - frontend
    environment:
      - ExtraSettingNotInSettingsFile=Development
      - ConnectionStrings:CUSTOMCONNSTR_MONGO="Server=TestServer;Database=TestDb;Persist Security Info=True;User ID=TestUser;Password=testpassword;MultipleActiveResultSets=true"

    ports:
      - 8010:80

